name: Podcast Build and Test

on:
  push:
    paths:
      - 'podcast/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        # Install vitest and fast-xml-parser without specifying a version.
        # Using @latest in the version spec caused npm to parse the
        # version incorrectly in GitHub Actions, so we omit it here.
        run: |
          npm install vitest --legacy-peer-deps
          npm install fast-xml-parser --legacy-peer-deps
      - name: Build RSS feed
        run: node podcast/build_feed.js
      - name: Run tests
        run: npx vitest run
