name: Podcast Build and Test
on:
  push:
    paths:
      - 'podcast/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: podcast
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Build RSS feed
        run: npm run build:feed
      - name: Run tests
        run: npm test -- --run
